---

name: Lint
on: [push]

jobs:

  lint-js:
    name: Lint Javascript code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint Javascript
        run: npm run lint

  lint-rust:
    name: Test Rust code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --check
      - name: Lint Rust
        run: cargo clippy
      - name: Test Rust
        run: cargo test
